import { BookOpen, Download, Share2 } from 'lucide-react';
import { motion } from 'framer-motion';
import { jsPDF } from 'jspdf';
import MarkdownRenderer from './MarkdownRenderer';

const SafeMarkdown = ({ content }) => {
  return <MarkdownRenderer content={content} />;
};

// Strip inline markdown syntax for clean PDF text
const stripInline = (text) =>
  text
    .replace(/\*\*(.+?)\*\*/g, '$1')   // **bold**
    .replace(/\*(.+?)\*/g, '$1')        // *italic*
    .replace(/__(.+?)__/g, '$1')        // __bold__
    .replace(/_(.+?)_/g, '$1')          // _italic_
    .replace(/`(.+?)`/g, '$1')          // `code`
    .replace(/~~(.+?)~~/g, '$1')        // ~~strikethrough~~
    .replace(/\[(.+?)\]\(.+?\)/g, '$1') // [link](url)
    .trim();

const exportToPDF = (notes) => {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 48;
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  // Header bar
  doc.setFillColor(99, 102, 241); // primary indigo
  doc.rect(0, 0, pageWidth, 36, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(255, 255, 255);
  doc.text('Mentixo AI — Study Notes', margin, 24);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(new Date().toLocaleDateString([], { dateStyle: 'long' }), pageWidth - margin, 24, { align: 'right' });

  y = 60;

  // Parse and render lines
  const lines = notes.split('\n');

  lines.forEach((line) => {
    // Page break check
    if (y > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }

    if (line.startsWith('#### ')) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(100, 100, 100);
      doc.text(line.replace(/^#{1,6}\s+/, ''), margin, y);
      y += 16;
    } else if (line.startsWith('### ')) {
      // H3
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(80, 80, 80);
      doc.text(line.replace(/^#{1,6}\s+/, ''), margin, y);
      y += 18;
    } else if (line.startsWith('## ')) {
      // H2
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.setTextColor(60, 60, 60);
      doc.text(line.replace(/^#{1,6}\s+/, ''), margin, y);
      y += 22;
    } else if (line.startsWith('# ')) {
      // H1
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(18);
      doc.setTextColor(99, 102, 241);
      doc.text(line.replace(/^#{1,6}\s+/, ''), margin, y);
      y += 28;
    } else if (line.startsWith('- ') || line.startsWith('* ')) {
      // Bullet point
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(50, 50, 50);
      const bulletText = stripInline(line.replace(/^[-*] /, ''));
      const wrapped = doc.splitTextToSize(`• ${bulletText}`, maxWidth - 12);
      wrapped.forEach((wl) => {
        if (y > pageHeight - margin) { doc.addPage(); y = margin; }
        doc.text(wl, margin + 8, y);
        y += 15;
      });
    } else if (line.trim() === '') {
      // Empty line — small gap
      y += 6;
    } else {
      // Normal paragraph
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(50, 50, 50);
      const wrapped = doc.splitTextToSize(stripInline(line), maxWidth);
      wrapped.forEach((wl) => {
        if (y > pageHeight - margin) { doc.addPage(); y = margin; }
        doc.text(wl, margin, y);
        y += 15;
      });
    }
  });

  // Footer on last page
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.setTextColor(180, 180, 180);
  doc.text('Generated by Mentixo AI', margin, pageHeight - 20);
  doc.text(`Page ${doc.internal.getNumberOfPages()}`, pageWidth - margin, pageHeight - 20, { align: 'right' });

  doc.save('mentixo-notes.pdf');
};

const NotesViewer = ({ notes, topic }) => {
  if (!notes) return null;

  return (
    <motion.div 
      initial={{ opacity: 0, scale: 0.98 }}
      animate={{ opacity: 1, scale: 1 }}
      className="p-8 space-y-8"
    >
      <div className="flex justify-between items-center border-b border-white/5 pb-6">
        <div className="flex items-center gap-3">
          <div className="p-2.5 bg-emerald-500/10 rounded-xl shadow-[0_0_15px_rgba(16,185,129,0.1)]">
            <BookOpen className="w-6 h-6 text-emerald-500" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-white tracking-tight">
              {topic || 'Mentixo Study Notes'}
            </h2>
            <p className="text-[10px] text-emerald-500 font-bold uppercase tracking-widest mt-0.5">Comprehensive Guide</p>
          </div>
        </div>
        <div className="flex gap-3">
          <button
            onClick={() => navigator.clipboard?.writeText(notes)}
            className="p-3 rounded-xl bg-white/5 hover:bg-white/10 text-text-muted hover:text-white transition-all border border-white/5"
            title="Copy to clipboard"
          >
            <Share2 className="w-5 h-5" />
          </button>
          <button
            onClick={() => exportToPDF(notes)}
            className="flex items-center gap-2 px-5 py-2.5 bg-primary hover:bg-indigo-500 text-white rounded-xl transition-all font-bold shadow-lg shadow-primary/20 hover:scale-105 active:scale-95"
          >
            <Download className="w-4 h-4" />
            Export PDF
          </button>
        </div>
      </div>
      
      <div className="bg-background/30 rounded-[2rem] p-8 border border-white/5 shadow-inner">
        <SafeMarkdown content={notes} />
      </div>

      <div className="pt-8 border-t border-white/5 flex items-center justify-between text-[10px] font-bold text-text-muted uppercase tracking-widest">
        <span>Generated by Mentixo AI</span>
        <span>{new Date().toLocaleDateString()}</span>
      </div>
    </motion.div>
  );
};

export default NotesViewer;
